### PR TITLE
Download subtitle files

### PR DESCRIPTION
**Pull request by Pavol-Beskid**
- added a download button to SubtitleEditor view for downloading subtitles in WebVTT file.

### CODE REVIEW

**Comment by Arnei** [comment]
Hi Pavol-Beskid,
thanks for contributing! I'll try and see to it that this gets merged before the end of the month.

**Review by Arnei — APPROVED** [review]
Code looks code and does what it says, approved from my side.

Short FYI: You don't *need* to provide a translation for every language, only `en-US` is fine. Translation is then later done in CrowdIn.

**Comment by Arnei** [comment]
Quick screen grab (for people who want to see how it looks, but don't want to install this PR themselves):
[Bildschirmaufzeichnung vom 2023-10-26, 09-14-14.webm](https://github.com/opencast/opencast-editor/assets/14070005/da396a2f-4f1f-4084-a60a-616c2c0a38e7)

**Comment by gregorydlogan** [comment]
ICLA is now on file, so this is good to go

**Pull request merged**
