### PR TITLE
Fix #1186, incorrect color of btn icons on hover

### LINKED ISSUE #1186: High contrast: Icon color of buttons in track selection view should invert on hover
These appear to be the only buttons that don't do that. The icon color should match the text color.
Bildschirmfoto 2023-10-26 um 13 02 45Bildschirmfoto 2023-10-26 um 12 56 19

### PR DESCRIPTION
**Pull request by maheshchandra10**
Fixes #1186 

color property of the icon-class is overriding the color property of button-class on hover.

### CODE REVIEW

**Review by owi92 — APPROVED** [review]
Cool, thanks for the fix! Once you have filed the required ICLA thingy (see the gh actions comment above), I'd say this can get merged.

**Comment by maheshchandra10** [comment]
> Cool, thanks for the fix! Once you have filed the required ICLA thingy (see the gh actions comment above), I'd say this can get merged.

I filled it as soon as I got this error, but I guess it still hasn't updated where it's supposed to be updated :(

**Comment by KatrinIhler** [comment]
Maybe it still needs some time before that ICLA is processed (a list of the currently completed ICLA's can be found here: https://licensing.apereo.org/).

**Comment by gregorydlogan** [comment]
ICLA is now on file, so this is good to go

**Pull request merged**
