### PR TITLE
Remove all segments button

### PR DESCRIPTION
**Pull request by dennis531**
Contains the following changes:
- Adds a button to delete all segments
- ~~Adds a button for each segment to delete corresponding segment~~

Ref #1083

### CODE REVIEW

**Comment by lkiesow** [comment]
I think you misunderstood #1083. I think what @kweingaertne wants is not to mark the content for removal, but to be able to quickly remove all segments itself. Right now, you would do that by starting somewhere and hitting the “Merge Left/Right” buttons over and over again.

Marking all segments for removal doesn't really make sense because you would end up with a 0 seconds long video file which should then fail to process as Opencast would tell you that this doesn't really make sense :D

**Comment by lkiesow** [comment]
I'm also not the biggest fan of the icon on the timeline. The old editor had several of them and I would like to not see them creep back one after another. Maybe instead as a “pro” feature to easily access the functionality implement #943 instead?

What do you think, @kweingaertne?

**Comment by lkiesow** [comment]
Finally (for the next time), having one feature/change pre pull request makes these changes easier to discuss, review and merge.

**Comment by dennis531** [comment]
Now the button allows to merge all segments into a single segment. 
Additionally, the delete button on each segment is removed.

**Comment by dennis531** [comment]
> Usually when merging segments, the resulting segment inherits the "deleted state" of the previously selected segment. So if I select a "blue" segment and merge it with "red", the resulting segment is "blue". This is not true for the specific case in which I select a "red" segment" and merge it _left_ with a "blue" segment. The resulting segment is "blue" instead of "red". Could you fix that?

Thanks for noticing. It should be fixed now.

**Review by Arnei — APPROVED** [review]

**Comment by dennis531** [comment]
> > Usually when merging segments, the resulting segment inherits the "deleted state" of the previously selected segment. So if I select a "blue" segment and merge it with "red", the resulting segment is "blue". This is not true for the specific case in which I select a "red" segment" and merge it _left_ with a "blue" segment. The resulting segment is "blue" instead of "red". Could you fix that?
> 
> Thanks for noticing. It should be fixed now.

During solving the merge conflicts, I have noticed that this problem was still present. Hopefully, this is solved now.

**Review by Arnei — APPROVED** [review]

**Pull request merged**
