### PR TITLE
Add context menu for cutting actions

### LINKED ISSUE #943: Add right click menu for cutting
Similar to the right-click context menu Element offers (see below), we should implement a context menu for the editor view to quickly remove or modify segments. This should be an additional menu though.

Screenshot from 2022-12-24 10-54-57

### PR DESCRIPTION
**Pull request by dennis531**
Displays a context menu over the cutting timeline when the user clicks on it with the right (secondary) mouse button.

Closes #943

### CODE REVIEW

**Review by lkiesow — APPROVED** [review]
Looks good to me

**Comment by kai-wng-uos** [comment]
I really like this change!

**Comment by ziegenberg** [comment]
Shouldn't we only change the en-us.json locale file because Crowdin does the translation?

**Comment by dennis531** [comment]
I reverted the tranlation files as suggested in https://github.com/opencast/opencast-editor/pull/1311#issuecomment-2086343395.

**Comment by lkiesow** [comment]
Shouldn't really matter since they would just be overwritten by the Crowdin changes. But it's reverted now, so nevermind.
Merging.

**Pull request merged**
