### PR TITLE
Change wordings in finish menu

### PR DESCRIPTION
**Pull request by dennis531**
Change the the wording of the "Start processing" button to "Save and publish changes" to better differentiate the buttons. Additionally, this should highlight that videos can be published with this button.

I haven't changed the existing translations, as I don't know what to do with them.

Related #1131

### CODE REVIEW

**Comment by ziegenberg** [comment]
I don't know if that change is desirable. The workflow may or may not publish the video. How about "Save and start processing"?

**Comment by dennis531** [comment]
> I don't know if that change is desirable. The workflow may or may not publish the video. How about "Save and start processing"?

I had the same thoughts when I changed the texts. I agree that we should keep "processing" and append "save" to the text.

**Comment by KatrinIhler** [comment]
Change looks fine, but i wonder how we can trigger a re-translation of this. Maybe we should rename the translation key (append `new` or something)?

**Comment by ziegenberg** [comment]
Shouldn't Crowdin handle those cases? The English string has changed, so it comes up again for all translators.

**Comment by KatrinIhler** [comment]
> Shouldn't Crowdin handle those cases? The English string has changed, so it comes up again for all translators.

I don't know if that's how it works? If it is, that'd be great.

**Comment by ziegenberg** [comment]
Maybe @gregorydlogan or @lkiesow, who know how Crowdin works, want to chime in. We should document "How to handle translation" afterwards.

**Comment by KatrinIhler** [comment]
From the dev meeting: We assume that changing the English translation string will prompt re-translation into the other languages in Crowdin. :)

**Comment by gregorydlogan** [comment]
Will clarify in the docs as a separate PR, but yes that's my understanding.  Changing the translated (non-en_US) strings is frowned upon because they will blindly be overwritten by the Crowdin bot and this can also cause merge conflicts going upwards towards Develop.

**Comment by dennis531** [comment]
@gregorydlogan Thanks for the clarification. I reverted the german translations.

**Pull request merged**
