### PR TITLE
Made the segment border "draggable"

### LINKED ISSUE #68: Make segment border click n' draggable
It would be nice if a user could change the position of a cut without being forced to delete it first and then recreate it. One way this could be achieved is the take make the borders between the segments click and draggable.

### PR DESCRIPTION
**Pull request by Arnei**
Click and drag on a segment border to move it. Still WIP, but feedback is welcome.

Known issues:
- Scrubber always jumps to border when trying to drag it.
- Missing mouse over indicator for hovering over a border.
- Dragging a border "over the edge" (out of the timeline) may break border dragging.

Resolves #68.

### CODE REVIEW

**Comment by Arnei** [comment]
Fixed issues mentioned in the initial comment.

There are still warnings being thrown, for which I am unsure on how to fix them (when first cutting, and when dragging a segment border out of the timeline).

**Comment by lkiesow** [comment]
A cursor like `col-resize` seems like a better choice:

**Comment by lkiesow** [comment]
When you cut, the scrubber overlays the segment marker but if you try dragging the scrubber, you drag the segment:

https://user-images.githubusercontent.com/1008395/121021138-597da280-c7a1-11eb-9197-1cd53554dee2.mp4

**Comment by lkiesow** [comment]
When dragging a segment over another one, the segment merges with the next one. But if you drag it over a second one, it will not merge with both, which is unexpected. I would suggest to either make the separator stop at the next segment, visually highlighting that you can only remove one segment by dragging, or allow multiple segments to be merged.


https://user-images.githubusercontent.com/1008395/121021754-ff311180-c7a1-11eb-800f-8d1a13bb8919.mp4

**Comment by lkiesow** [comment]
The UI starts jumping around when you start dragging for no apparent reason:


https://user-images.githubusercontent.com/1008395/121024788-d65e4b80-c7a4-11eb-9134-ff9e49bb078e.mp4

**Pull request closed without merging**
