### PR TITLE
Add subtitle delete button

### PR DESCRIPTION
**Pull request by geichelberger**
This adds a subtitle delete button to the subtitle editor, which allows the deletion of newly created subtitles or already existing ones.

Requires https://github.com/opencast/opencast/pull/6361

image

### CODE REVIEW

**Comment by gregorydlogan** [comment]
Adding this precludes updating the editor in 16.x anymore, which (as discussed in the dev meeting) is ok since we're not going to update the editor in 16 anymore.

**Comment by geichelberger** [comment]
I thought the subtitle slice handled the state, is there another state for starting the workflow?

**Comment by Arnei** [comment]
Yes, there are `workflowPostSlice.ts` and `workflowPostAndProcessSlice.ts`.

**Comment by geichelberger** [comment]
The PR https://github.com/opencast/opencast-editor/pull/1413 should help with the duplicate save logic. After merging, I will rebase this.

**Review by Arnei — APPROVED** [review]
Working fine now!

**Pull request merged**
