### PR TITLE
Improve visibility of input fields

### LINKED ISSUE #932: Subtitle editor, make input fields better visible
Input fields for subtitle text and time marks are nicely formated in dark mode: Input fields have other background colors than the page background and a clear visible border: 

2022-12-07 11_54_15-Greenshot

We should make similar things with the "default" / white skin: 

2022-12-07 11_54_14-Greenshot

Either making the input background light gray or the general background (then for all pages)!

### PR DESCRIPTION
**Pull request by dennis531**
Shows a slightly grey (whitesmoke) background and white input fields in light mode.

This changes should make the input fields better visible, since they are currently displayed in the same background color.

Resolves #932

### CODE REVIEW

**Review by Arnei — APPROVED** [review]
Works and looks reasonable to me.

While I'd be fine merging this as is, what do you think about using a different background color for the main menu vs the main content? So for example, the keep `snow` color for the main menu and only set the main content part to `whitesmoke`?

**Comment by dennis531** [comment]
It is a good idea, as it would better separate the menu from the content.

**Comment by dennis531** [comment]
The interface with a white navigation menu looks like this:
image

Should the buttons be displayed in a lighter grey?

**Comment by Arnei** [comment]
> Should the buttons be displayed in a lighter grey?

Hmm, I don't know, what do you think? :D

**Comment by dennis531** [comment]
I would suggest a lighter grey like the following:
image

**Comment by Arnei** [comment]
Seems fine by me. Might wanna do a contrast check with e.g. the WAVE browser add-on to check if the contrast is still high enough (for accessibility reasons).

**Comment by Arnei** [comment]
Seems like the it doesn't make much of a difference. I'm fine merging this either way, I'll let you decide if you want to make more changes.

**Comment by dennis531** [comment]
> Seems fine by me. Can you do a contrast check with e.g. the WAVE browser add-on to check if the contrast is still high enough (for accessibility reasons).

The contrast checker could not detect any constrast issues.

> Seems like the it doesn't make much of a difference. I'm fine merging this either way, I'll let you decide if you want to make more changes.

I added my latter suggestion with the lighter buttons.

**Review by Arnei — APPROVED** [review]

**Pull request merged**
